version: '3.9'
services:
  dex-postgres-db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - DATABASE_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: dex-postgres-db
    volumes:
      - pgdata:/data/postgres
  dex-pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: dex-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=${PGADMIN_LISTEN_PORT}
    ports:
      - '80:80'
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - dex-postgres-db
  dex-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: tusharchy/nest-and-postgres-application:latest
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - POSTGRES_SYNC=${POSTGRES_SYNC}
      - JWT_SECRET=${JWT_SECRET}

    ports:
      - '3333:3333' # expose-to-the-world : only-in-the-docker
    container_name: dex-api
    depends_on:
      - dex-postgres-db
    # volumes:
    #   - .:/app
    #   - /app/node_modules
volumes:
  pgdata:
  pgadmin-data:
networks:
  server-net:
    driver: bridge
