export const enum CommandsError {
  USER_ID_REQUIRED = 'User Id required',
  TOKEN_A_ADDRESS_REQUIRED = 'Address A required',
  TOKEN_B_ADDRESS_REQUIRED = 'Address B required',
  TOKEN_A_AMOUNT_REQUIRED = 'Amount A required',
  TOKEN_B_AMOUNT_REQUIRED = 'Amount B required',
  SLIPPAGE_REQUIRED = 'Slippage required',
  POOL_ADDRESS_NOT_FOUND = 'Pool Address not found',
  POOL_ADDRESS_REQUIRED = 'Pool Address required',
  POOL_ID_REQUIRED = 'Pool Id required',
  TRANSACTION_UNSUCCESSFUL = 'Transaction unsuccessful',
  TRANSACTION_NOT_FOUND = 'Transaction not found',
  CONTRACT_RECEIPT_UNSUCCESSFUL = 'Contract receipt unsuccessful',
  CONTRACT_RECEIPT_NOT_FOUND = 'Contract receipt not found',
  METAMASK_ADDRESS_REQUIRED = 'Metamask address required',
  ACCOUNT_ID_REQUIRED = 'Account id required',
  POSITION_AMOUNT_REQUIRED = 'Staking amount required',
  STAKEABLE_POOL_DOES_NOT_AVAILABLE = 'Stakeable pool does not available',
  FLOW_IS_NOT_DEFINED = 'Flow not defined',
  SLIPPAGE_LIMITED_IN_10_PERCENT = 'Max Slippage 10%',
  TOKEN_PAIR_ALREADY_EXIST = 'Token pair already exist!'
}
