export const enum Flows {
  ADD_LIQUIDITY = 'ADD_LIQUIDITY',
  CLAM_REWARDS = 'CLAM_REWARDS',
  CREATE_PAIR = 'CREATE_PAIR',
  REMOVE_LIQUIDITY = 'REMOVE_LIQUIDITY',
  SWAP = 'SWAP',
  STAKE_TOKEN = 'STAKE_TOKEN',
  SET_STAKING = 'SET_STAKING',
  APPROVE_TOKEN = 'APPROVE_TOKEN'
}
